// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// ledgrcore-init.cpp
std::string ledgrcore_spike_cpp_hello();
extern "C" SEXP _ledgrcorespike_ledgrcore_spike_cpp_hello() {
  BEGIN_CPP11
    return cpp11::as_sexp(ledgrcore_spike_cpp_hello());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_ledgrcorespike_ledgrcore_spike_cpp_hello", (DL_FUNC) &_ledgrcorespike_ledgrcore_spike_cpp_hello, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ledgrcorespike(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
