# Generated by cpp11: do not edit by hand

k1_cpp_fold_strat_R_handler_R <- function(bars, initial_cash, strategy_callback, output_handler, output_acc) {
  .Call(`_ledgrcorespike_k1_cpp_fold_strat_R_handler_R`, bars, initial_cash, strategy_callback, output_handler, output_acc)
}

k1_cpp_fold_strat_R_handler_inline <- function(bars, initial_cash, strategy_callback) {
  .Call(`_ledgrcorespike_k1_cpp_fold_strat_R_handler_inline`, bars, initial_cash, strategy_callback)
}

k1_cpp_fold_strat_static_handler_R <- function(bars, initial_cash, output_handler, output_acc) {
  .Call(`_ledgrcorespike_k1_cpp_fold_strat_static_handler_R`, bars, initial_cash, output_handler, output_acc)
}

k1_cpp_fold_strat_static_handler_inline <- function(bars, initial_cash) {
  .Call(`_ledgrcorespike_k1_cpp_fold_strat_static_handler_inline`, bars, initial_cash)
}

ledgrcore_spike_cpp_hello <- function() {
  .Call(`_ledgrcorespike_ledgrcore_spike_cpp_hello`)
}
